[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "civic-lib"
version = "0.1.0"
description = "Shared internal utility library for Civic Interconnect Agents"
authors = [
    { name="Civic Interconnect", email="info@civic-interconnect.org" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "loguru",
    "python-dotenv",
    "PyYAML",
    "requests",
    "gql[aiohttp]",
]

[project.urls]
"Homepage" = "https://github.com/civic-interconnect/civic-interconnect-lib"
"Source" = "https://github.com/civic-interconnect/civic-interconnect-lib"
